name: deploy Nodejs application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Verify key format
        run: |
            echo "$SSH_KEY" | head -1
            echo "$SSH_KEY" | tail -1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
           echo "❌ SSH_PRIVATE_KEY is empty or not set!"
             else
              echo "✅ SSH_PRIVATE_KEY is set"
                 fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_URL }}
          username: root
          port: 3001   
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/madhavsaibhushan/nodejs-application-deploy-git-actions
            git pull
            docker compose up -d --build
